EventManger/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from EventManger.views import homepage
from Dj.views import dj_list, dj_detail, dj_create
from Club.views import club_detail, club_list, club_create
from Event.views import event_create, event_detail, event_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', homepage, name='home'),
    path('djs/', dj_list, name='dj-list'),
    path('dj/<int:id>/', dj_detail, name='dj-detail'),
    path('dj/create', dj_create, name='dj-create'),
    path('clubs/', club_list, name='club-list'),
    path('club/<int:id>', club_detail, name='club-detail'),
    path('club/create', club_create, name='club-create'),
    path('events/', event_list, name='event-list'),
    path('event/<int:id>', event_detail, name='event-detail'),
    path('event/create', event_create, name='event-create')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Club/models.py
from django.db import models


# Create your models here.
class Club(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    ubication = models.CharField(max_length=200)
    creation_date = models.DateTimeField()
    photo = models.ImageField(upload_to='club/')

    def __str__(self):
        return self.name

Dj/models.py
from django.db import models

# Create your models here.
class Dj(models.Model):
    name = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    style = models.CharField(max_length=100)
    best_known = models.CharField(max_length=100)
    description = models.TextField()
    photo = models.ImageField(upload_to='dj/')
    audio = models.FileField(upload_to='dj_audio/')

    def __str__(self):
        return self.name

Event/models.py
from django.db import models

from Dj.models import Dj
from Club.models import Club


# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='event/')
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    dj = models.ManyToManyField(Dj, related_name='event')

Club/forms.py
from django import forms
from .models import Club


class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['name', 'ubication', 'creation_date', 'description', 'photo']

Dj/forms.py
from django import forms
from .models import Dj

class DjForm(forms.ModelForm):
    class Meta:
        model = Dj
        fields = ['name', 'nationality', 'style', 'best_known', 'description', 'photo', 'audio']

Event/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'date', 'price', 'photo', 'club', 'dj']

Club/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from Club.models import Club
from Club.forms import ClubForm


# Create your views here.

def club_list(request):
    clubs = Club.objects.all()
    return render(request, 'Club/list.html', {'clubs': clubs})


def club_detail(request, id):
    clubs = Club.objects.filter(id=id).first()
    return render(request, 'Club/detail.html', {'clubs': clubs})


@login_required
def club_create(request):
    if request.method == 'POST':
        form = ClubForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('club-list')
    else:
        form = ClubForm()
    return render(request, 'Club/add.html', {'form': form})

Dj/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from Dj.forms import DjForm
from Dj.models import Dj


# Create your views here.

def dj_list(request):
    # rename the view function
    djs = Dj.objects.all()
    return render(request, 'dj/list.html', {'djs': djs})


def dj_detail(request, id):
    dj = Dj.objects.filter(id=id).first()
    return render(request, 'dj/detail.html', {'dj': dj})


@login_required
def dj_create(request):
    if request.method == 'POST':
        print(request.POST)
        form = DjForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('dj-list')
    else:
        form = DjForm()
    return render(request, 'dj/add.html', {'form': form})

Event/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from Club.models import Club
from Event.forms import EventForm
from Event.models import Event


# Create your views here.
def event_list(request):
    # rename the view function
    events = Event.objects.all()
    return render(request, 'event/list.html', {'events': events})


def event_detail(request, id):
    event = Event.objects.filter(id=id).first()
    return render(request, 'event/detail.html', {'event': event})


@login_required
def event_create(request):

    clubs = Club.objects.all().order_by('name')
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('event-list')
    else:
        form = EventForm()
    return render(request, 'event/add.html', {'form': form, 'clubs': clubs})

EventManger/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect


def homepage(request):
    return render(request,'home.html')

def LogoutView(request):
    logout(request)
    return redirect('home')
    # Redirect to a success page.

templates/Club/add.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <section class="h-100 gradient-form">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 ">
                                    <p class="h1">AÑADIR CLUB</p>

                                    <form method="post" enctype="multipart/form-data" action="{% url 'club-create' %}">
                                        {% csrf_token %}

                                        <div class="form-outline mb-4">
                                            <div class="form__group field">
                                                <input type="text" class="form__field" id="name" name="name"
                                                       placeholder="Nombre"
                                                       required="">
                                                <label for="name" class="form__label">Nombre</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="text" class="form__field" placeholder="Ubicacion"
                                                       name="ubication" id="ubication" required="">
                                                <label for="ubication" class="form__label">Ubicacion</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="date" class="form__field" placeholder="Fecha de apertura"
                                                       name="creation_date" id="creation_date" required="">
                                                <label for="creation_date" class="form__label">Fecha de apertura</label>
                                            </div>
                                            <div class="form-floating mt-3">
                                                <textarea class="form-control" placeholder="Descripcion"
                                                          id="description" name="description"
                                                          style="height: 100px"></textarea>
                                                <label for="description">Descripcion</label>
                                            </div>
                                            <div class="mb-2">
                                                <label for="id_photo" class="mt-3">
                                                    <p class="login_button" id="photo_label">
                                                        <i class="bi bi-cloud-arrow-up-fill"></i>
                                                        SUBIR FOTO
                                                    </p>
                                                </label>
                                                <input type="file" name="photo" accept="image/*" required=""
                                                       class="invisible" id="id_photo">
                                            </div>
                                            <div class="row mb-2">
                                            </div>

                                        </div>


                                        <div class="text-center pt-1 mb-5 pb-1">
                                            <button class="login_button" type="submit">
                                                Añadir
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center login_gradient">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">¡Ya sabemos donde va a ser la fiesta, solo faltas TU!</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        const inputFile = document.getElementById('id_photo');
        const fileNameDisplay = document.getElementById('photo_label');

        inputFile.addEventListener('change', function () {
            if (inputFile.files.length > 0) {
                fileNameDisplay.textContent = inputFile.files[0].name;
            } else {
                fileNameDisplay.textContent = '';
            }
        });
    </script>



{% endblock %}

templates/Club/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid bg-dark">
        <div class="row">
            <div class="col-md-12 p-0">
                <div class="position-relative" style="overflow: hidden; height: 600px;">
                    <img src="{{ clubs.photo.url }}" class="img-fluid w-100 h-100 rounded" style="object-fit: cover;"
                         alt="{{ clubs.name }}">
                    <div class="position-absolute bottom-0 start-0 p-3">
                        <h1 class="text-white"
                            style="font-family: sans-serif; font-size: 3em; font-weight: 900;text-shadow: 2px 2px 0px orange;">{{ clubs.name.upper }}</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8">
                <div class="text-white">
                    <div class="card-body">
                        <p><strong>Ubicacion:</strong> {{ clubs.ubication }}</p>
                        <p><strong>Fecha de apertura:</strong> {{ clubs.creation_date }}</p>
                        <p><strong>Descripción:</strong></p>
                        <p class="card-text text-justify">{{ clubs.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Club/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="h-100 gradient-form">
        <div class="container py-5 h-100">
            {% if user.is_authenticated %}
                <a href="{% url 'club-create' %}">
                    <button class="add-button float-end"><i class="bi bi-plus"></i> Add</button>
                </a>
            {% endif %}
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10 col-11">
                    <div class="rounded-3 text-black row d-flex">
                        {% for club in clubs %}
                            <div class="col-12 col-lg-6">
                                <a href="{% url 'club-detail' club.id %}">
                                    <div class="flip-card">
                                        <div class="flip-card-inner">
                                            <div class="flip-card-front">
                                                <img class=" img-fluid flip-card-img"
                                                     src="{{ club.photo.url }}"/>
                                            </div>
                                            <div class="flip-card-back">
                                                <p class="title">{{ club.name.upper }}</p>
                                                <p>Ubicacion: {{ club.ubication }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/Dj/add.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <section class="h-100 gradient-form">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 ">
                                    <p class="h1">AÑADIR DJ</p>
                                    <p>Campos obligatorios: {{ required_fields }}</p>

                                    <form method="post" enctype="multipart/form-data" action="{% url 'dj-create' %}">
                                        {% csrf_token %}

                                        <div class="form-outline mb-4">
                                            <div class="form__group field">
                                                <input type="text" class="form__field" id="name" name="name"
                                                       placeholder="Nombre"
                                                       required="">
                                                <label for="name" class="form__label">Nombre</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="text" class="form__field" placeholder="Nacionalidad"
                                                       name="nationality" id="nationality" required="">
                                                <label for="nationality" class="form__label">Nacionalidad</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="text" class="form__field" placeholder="Estilo"
                                                       name="style" id="style" required="">
                                                <label for="style" class="form__label">Estilo</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="text" class="form__field" placeholder="Mas conocido por:"
                                                       name="best_known" id="best_known" required="">
                                                <label for="best_known" class="form__label">Mas conocido por:</label>
                                            </div>
                                            <div class="form-floating mt-3">
                                                <textarea class="form-control" placeholder="Descripcion"
                                                          id="description" name="description"
                                                          style="height: 100px"></textarea>
                                                <label for="description">Descripcion</label>
                                            </div>
                                            <div class="mb-2">
                                                <label for="id_photo" class="mt-3">
                                                    <p class="login_button" id="photo_label">
                                                        <i class="bi bi-cloud-arrow-up-fill"></i>
                                                        SUBIR FOTO
                                                    </p>
                                                </label>
                                            </div>
                                            <div class="">
                                                <label for="id_audio" class="mt-1">
                                                    <p class="login_button" id="audio_label">
                                                        <i class="bi bi-cloud-arrow-up-fill"></i>
                                                        SUBIR AUDIO
                                                    </p>
                                                </label>
                                                <input type="file" name="audio" accept="audio/*" required=""
                                                       class="invisible" id="id_audio">

                                                <input type="file" name="photo" accept="image/*" required=""
                                                       class="invisible" id="id_photo">
                                            </div>

                                        </div>


                                        <div class="text-center pt-1 mb-5 pb-1">
                                            <button class="login_button" type="submit">
                                                Añadir
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center login_gradient">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">¡La fiesta está por alcanzar su máximo esplendor!</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        const photoFile = document.getElementById('id_photo');
        const photoNameDisplay = document.getElementById('photo_label');

        photoFile.addEventListener('change', function () {
            if (photoFile.files.length > 0) {
                photoNameDisplay.textContent = photoFile.files[0].name;
            } else {
                photoNameDisplay.textContent = '';
            }
        });

        const inputFile = document.getElementById('id_audio');
        const fileNameDisplay = document.getElementById('audio_label');

        inputFile.addEventListener('change', function () {
            if (inputFile.files.length > 0) {
                fileNameDisplay.textContent = inputFile.files[0].name;
            } else {
                fileNameDisplay.textContent = '';
            }
        });
    </script>



{% endblock %}

templates/Dj/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid bg-dark">
        <div class="row">
            <div class="col-md-12 p-0">
                <div class="position-relative" style="overflow: hidden; height: 600px;">
                    <img src="{{ dj.photo.url }}" class="img-fluid w-100 h-100 rounded" style="object-fit: cover;"
                         alt="{{ dj.name }}">
                    <div class="position-absolute bottom-0 start-0 p-3">
                        <h1 class="text-white"
                            style="font-family: sans-serif; font-size: 3em; font-weight: 900;text-shadow: 2px 2px 0px orange;">{{ dj.name.upper }}</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8">
                <div class="text-white">
                    <div class="card-body">

                        <p><strong>Cancion mas escuchada:</strong><br/>
                            {% if dj.audio %}
                                <audio controls class="mt-2 ">
                                    <source src="{{ dj.audio.url }}" type="audio/mpeg">
                                    Tu navegador no soporta la reproducción de audio.
                                </audio>
                            {% else %}
                                <p>No se ha proporcionado una cancion para este DJ.</p>
                            {% endif %}
                        </p>

                        <p><strong>Nacionalidad:</strong> {{ dj.nationality }}</p>
                        <p><strong>Estilo:</strong> {{ dj.style }}</p>
                        <p><strong>Mejor conocido por:</strong> {{ dj.best_known }}</p>
                        <p><strong>Descripción:</strong></p>
                        <p class="card-text text-justify">{{ dj.description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/Dj/list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="h-100 gradient-form">
        <div class="container py-5 h-100">
            {% if user.is_authenticated %}
                <a href="{% url 'dj-create' %}">
                <button class="add-button float-end"><i class="bi bi-plus"></i> Add</button>
                </a>
            {% endif %}
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10 col-11">
                    <div class="rounded-3 text-black row d-flex">
                        {% for dj in djs %}
                            <div class="col-12 col-lg-6">
                                <a href="{% url 'dj-detail' dj.id %}">
                                    <div class="flip-card">
                                        <div class="flip-card-inner">
                                            <div class="flip-card-front">
                                                <img class=" img-fluid flip-card-img"
                                                     src="{{ dj.photo.url }}"/>
                                            </div>
                                            <div class="flip-card-back">
                                                <p class="title">{{ dj.name.upper }}</p>
                                                <p>Estilo: {{ dj.style }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/dj.html
{% extends "base.html" %}
{% load static %}
{% block title %} DJ {% endblock %}

{% block content %}
    <body>
    <h1>
        hola aquesta es la pagina de dj
    </h1>
    <figure class="mainimg">
        <div class="main-figure">
            <div class="full-image">
                <img class="img-fluid" src="{% static '/img/Medusa.png' %}" />
            </div>
        </div>
        <figcaption></figcaption>
    </figure>
    </body>

{% endblock %}

templates/event/add.html
{% extends "base.html" %}
{% load static %}
{% block content %}


    <section class="h-100 gradient-form">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-xl-10">
                    <div class="card rounded-3 text-black">
                        <div class="row g-0">
                            <div class="col-lg-6">
                                <div class="card-body p-md-5 ">
                                    <p class="h1">AÑADIR EVENTO</p>

                                    <form method="post" enctype="multipart/form-data" action="{% url 'event-create' %}">
                                        {% csrf_token %}

                                        <div class="form-outline mb-4">
                                            <div class="form__group field">
                                                <input type="text" class="form__field" id="title" name="title"
                                                       placeholder="Titulo" required="">
                                                <label for="title" class="form__label">Titulo</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="date" class="form__field" placeholder="Fecha" name="date"
                                                       id="date" required="">
                                                <label for="date" class="form__label">Fecha</label>
                                            </div>
                                            <div class="form__group field">
                                                <input type="text" class="form__field" placeholder="Precio" name="price"
                                                       id="price" required="">
                                                <label for="price" class="form__label">Precio</label>
                                            </div>

                                            <div class="mt-3"><p style="font-size: 17px;color: #aa2068;">Club:</p>
                                                {{ form.club }}
                                            </div>
                                            <div class="mt-3"><p style="font-size: 17px;color: #aa2068;">Djs
                                                participantes:</p>
                                                {{ form.dj }}
                                            </div>
                                        </div>
                                        <div class="form-floating mt-3">
                                            <textarea class="form-control" placeholder="Descripcion" id="description"
                                                      name="description" style="height: 100px"></textarea>
                                            <label for="description">Descripcion</label>
                                        </div>

                                        <div class="mb-2">
                                            <label for="id_photo" class="mt-3">
                                                <p class="login_button" id="photo_label">
                                                    <i class="bi bi-cloud-arrow-up-fill"></i>
                                                    SUBIR FOTO
                                                </p>
                                            </label>
                                            <input type="file" name="photo" accept="image/*" required=""
                                                   class="invisible" id="id_photo">
                                        </div>

                                        <div class="text-center pt-1 mb-5 pb-1">
                                            <button class="login_button" type="submit">
                                                Añadir
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-lg-6 d-flex align-items-center login_gradient">
                                <div class="text-white px-3 py-4 p-md-5 mx-md-4">
                                    <h4 class="mb-4">Tu ves un evento, ¡Nosotros nuevos recuerdos!</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        const inputFile = document.getElementById('id_photo');
        const fileNameDisplay = document.getElementById('photo_label');

        inputFile.addEventListener('change', function () {
            if (inputFile.files.length > 0) {
                fileNameDisplay.textContent = inputFile.files[0].name;
            } else {
                fileNameDisplay.textContent = '';
            }
        });
    </script>



{% endblock %}

templates/events.html
{% extends "base.html" %}
{% load static %}
{% block title %} DJ {% endblock %}

{% block content %}
    <body>
    <h1>
        hola aquesta es la pagina de events
    </h1>
    <figure class="mainimg">
        <div class="main-figure">
            <div class="full-image">
                <img class="img-fluid" src="{% static '/img/Medusa.png' %}" />
            </div>
        </div>
        <figcaption></figcaption>
    </figure>
    </body>

{% endblock %}

templates/local.html
{% extends "base.html" %}
{% load static %}
{% block title %} DJ {% endblock %}

{% block content %}
    <body>
    <h1>
        hola aquesta es la pagina de local
    </h1>
    <figure class="mainimg">
        <div class="main-figure">
            <div class="full-image">
                <img class="img-fluid" src="{% static '/img/Medusa.png' %}" />
            </div>
        </div>
        <figcaption></figcaption>
    </figure>
    </body>

{% endblock %}